BLOCK_SIZE = 32

PLAY_WIDTH = 8
PLAY_HEIGHT = 16

BORDER = 1

VISIBLE_WIDTH = PLAY_WIDTH + BORDER * 2
VISIBLE_HEIGHT = PLAY_HEIGHT + BORDER * 2

WINDOW_WIDTH = VISIBLE_WIDTH * BLOCK_SIZE
WINDOW_HEIGHT = VISIBLE_HEIGHT * BLOCK_SIZE